version: '3'

services:
  redismaster1:
    image: redis:6
    container_name: redismaster1
    ports:
      - "6379:6379"

#  redisslave1:
#    image: redis:6
#    container_name: redisslave1
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof redismaster1 6379
#    depends_on:
#      - redismaster1
#
#  redisslave2:
#    image: redis:6
#    container_name: redisslave2
#    ports:
#      - "6381:6379"
#    command: redis-server --slaveof redismaster1 6379
#    depends_on:
#      - redismaster1